(()=>{'use strict';
const songs=window.CUBABY_SONGS,refPack=window.CUBABY_REFS,timingPack=window.CUBABY_TIMINGS;
const SET=[28,35,16,33,4,31,9,10,37,38,1,40,30,42,14,17,11,18,43,26,27];
const byN=new Map(songs.map(s=>[+s.number,s])),refMeta=new Map((refPack.refs||[]).map(r=>[+r.n,r])),cache=new Map();
const $=id=>document.getElementById(id),U={state:$('state'),pos:$('pos'),score:$('score'),setpos:$('setpos'),next:$('next'),status:$('status'),select:$('setSelect'),lyrics:$('lyrics'),play:$('play'),diag:$('diag')};
let si=0,state='IDLE',ctx=null,stream=null,source=null,an=null,freq=null,time=null,raf=0,q=[],lastF=0,lastTick=0,lastLocal=0,lastTrans=0,pos=0,conf=0,line=-1,lowSince=0,gate=false,votes=0,voteSince=0,voteSong=0,timeline=[],logs=[];
function log(type,data){logs.push({t:Math.round(performance.now()),type:type,data:data||{}});if(logs.length>80)logs.shift();U.diag.textContent=logs.slice(-8).map(x=>x.type+' '+JSON.stringify(x.data)).join('\n');}
function fmt(s){s=Math.max(0,+s||0);return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');}
function setState(s,msg){state=s;U.state.textContent=s;U.state.className='pill '+(s==='LOCK'?'ok':s==='SILENT'?'warn':s==='ERROR'?'bad':'');if(msg)U.status.textContent=msg;log('STATE',{s,msg});}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function flat(song){const a=[];(song.sections||[]).forEach(sec=>(sec.lines||[]).forEach(t=>a.push({text:t,section:sec.label||''})));return a;}
function dense(n){const lines=flat(byN.get(+n)),raw=(timingPack.songs||{})[String(n)]||{},pts=(raw.points||[]).filter(p=>Number.isFinite(+p.t)&&Number.isInteger(+p.line)&&+p.line>=0&&+p.line<lines.length).sort((a,b)=>a.line-b.line),a=new Array(lines.length).fill(null);pts.forEach(p=>a[+p.line]=+p.t);if(!pts.length){for(let i=0;i<a.length;i++)a[i]=i*3;return a;}const dur=Number(raw.referenceDuration||raw.sourceDuration||0);if(pts.length&&pts[0].line===0&&dur>0&&pts[0].t>dur*.25){const start=Math.min(22,Math.max(8,dur*.07)),end=Math.max(start+20,dur*.88),step=(end-start)/Math.max(1,lines.length-1);for(let i=0;i<a.length;i++)a[i]=start+i*step;return a;}const sp=pts.length>1?Math.max(.8,Math.min(5,(pts[1].t-pts[0].t)/Math.max(1,pts[1].line-pts[0].line))):3;for(let i=0;i<pts[0].line;i++)a[i]=Math.max(0,pts[0].t-(pts[0].line-i)*sp);for(let k=0;k<pts.length-1;k++){const x=pts[k],y=pts[k+1];for(let i=x.line+1;i<y.line;i++)a[i]=x.t+(y.t-x.t)*((i-x.line)/(y.line-x.line));}for(let i=pts.at(-1).line+1;i<a.length;i++)a[i]=pts.at(-1).t+(i-pts.at(-1).line)*sp;for(let i=1;i<a.length;i++)a[i]=Math.max(a[i],a[i-1]+.25);return a;}
function render(){const n=SET[si],song=byN.get(n);timeline=dense(n);let g=0;U.lyrics.innerHTML='<div class="song-title">'+String(n).padStart(2,'0')+' · '+esc(song.title)+'</div>'+(song.sections||[]).map(sec=>'<section class="section"><div class="section-label">[AHORA] '+esc(sec.label||'')+'</div>'+(sec.lines||[]).map(x=>'<div class="line" data-i="'+(g++)+'">'+esc(x)+'</div>').join('')+'</section>').join('');line=-1;U.select.value=String(si);U.setpos.textContent='SET '+(si+1)+'/'+SET.length;U.next.textContent='Siguiente: '+(byN.get(SET[si+1])?.title||'FIN DEL SET');applyLine(pos,true);}
function lineFor(p){let lo=0,hi=timeline.length-1,ans=0;while(lo<=hi){const m=(lo+hi)>>1;if(timeline[m]<=p){ans=m;lo=m+1}else hi=m-1;}return ans;}
function setLine(i,force){const els=[...U.lyrics.querySelectorAll('.line')];if(!els.length)return;i=Math.max(0,Math.min(els.length-1,i));if(i===line&&!force)return;if(line>=0)els[line]?.classList.remove('active');line=i;const el=els[i];el.classList.add('active');el.scrollIntoView({block:'center',inline:'nearest',behavior:'auto'});log('LINE',{i,pos:+pos.toFixed(2)});}
function applyLine(p,force){if(timeline.length)setLine(lineFor(p),!!force);}
function b64(v){const s=atob(v),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a;}
function ref(n){n=+n;if(cache.has(n))return cache.get(n);const m=refMeta.get(n);if(!m)return null;const tb=b64(m.times),times=new Float32Array(m.count);for(let i=0;i<m.count;i++)times[i]=(tb[i*2]|(tb[i*2+1]<<8))/100;const r={n,count:m.count,dims:refPack.dims||36,times,features:b64(m.feat)};cache.set(n,r);return r;}
function feat(){const bins=freq,ny=(ctx?.sampleRate||48000)/2,L=[],bc=24,min=70,max=Math.min(5000,ny-1);for(let b=0;b<bc;b++){const f1=min*Math.pow(max/min,b/bc),f2=min*Math.pow(max/min,(b+1)/bc),i1=Math.max(1,Math.floor(f1/ny*bins.length)),i2=Math.max(i1+1,Math.floor(f2/ny*bins.length));let s=0,c=0;for(let i=i1;i<i2&&i<bins.length;i++){s+=Math.log1p(bins[i]);c++;}L.push(c?s/c:0);}let norm=Math.hypot(...L)||1;for(let i=0;i<24;i++)L[i]/=norm;const C=new Array(12).fill(0);for(let i=2;i<bins.length;i++){const f=i*ny/bins.length;if(f<80||f>3000)continue;const midi=69+12*Math.log2(f/440),pc=((Math.round(midi)%12)+12)%12;C[pc]+=Math.pow(bins[i]/255,2);}norm=Math.hypot(...C)||1;for(let i=0;i<12;i++)C[i]/=norm;return new Float32Array(L.concat(C));}
function score(qr,r,start,step){const need=Math.floor((qr.length-1)*step)+1;if(start<0||start+need>=r.count)return-Infinity;let total=0;for(let j=0;j<qr.length;j++){const ri=start+Math.round(j*step),base=ri*r.dims,v=qr[j];let ld=0,cd=0;for(let d=0;d<24;d++)ld+=v[d]*(r.features[base+d]/255);for(let d=24;d<36;d++)cd+=v[d]*(r.features[base+d]/255);total+=ld*.20+cd*.80;}return total/qr.length;}
function global(qr,r){let best=null;for(const step of [.9,1,1.1]){const need=Math.floor((qr.length-1)*step)+1;for(let i=0;i+need<r.count;i+=3){const sc=score(qr,r,i,step);if(!best||sc>best.score){const ei=Math.min(r.count-1,i+Math.round((qr.length-1)*step));best={score:sc,pos:r.times[ei]};}}}return best;}
function local(qr,r,expected){let best=null;for(const step of [.9,1,1.1]){const need=Math.floor((qr.length-1)*step)+1;for(let i=0;i+need<r.count;i++){const ei=Math.min(r.count-1,i+Math.round((qr.length-1)*step)),p=r.times[ei];if(Math.abs(p-expected)>5)continue;const sc=score(qr,r,i,step);if(!best||sc>best.score)best={score:sc,pos:p};}}return best;}
function rms(){an.getByteTimeDomainData(time);let s=0;for(const x of time){const v=(x-128)/128;s+=v*v;}return Math.sqrt(s/time.length);}
function labels(){U.pos.textContent='POS '+fmt(pos);U.score.textContent='AUDIO '+(conf?Math.round(conf*100)+'%':'—');}
async function start(){if(stream)return;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});ctx=new (window.AudioContext||window.webkitAudioContext)();source=ctx.createMediaStreamSource(stream);an=ctx.createAnalyser();an.fftSize=2048;an.smoothingTimeConstant=.55;source.connect(an);freq=new Uint8Array(an.frequencyBinCount);time=new Uint8Array(an.fftSize);q=[];lastTick=performance.now();gate=false;setState('ACQUIRE','Escuchando sólo la canción actual del SET para localizar posición.');U.play.textContent='❚❚ PAUSA';U.play.className='btn pause';loop();}catch(e){setState('ERROR','Micrófono: '+e.message);}}
function stop(keep){cancelAnimationFrame(raf);raf=0;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;try{source?.disconnect();}catch(e){}source=an=null;freq=time=null;q=[];U.play.textContent='▶ PLAY';U.play.className='btn play';setState('IDLE',keep?'Pausa manual · '+fmt(pos):'Detenido.');}
function reset(){stop(false);si=0;pos=0;conf=0;votes=0;voteSong=0;lowSince=0;gate=false;render();setState('IDLE','RESET · SET 1/'+SET.length+' · 0:00.');labels();}
function acquire(){const r=ref(SET[si]);if(!r||q.length<28)return;const c=global(q.slice(-28),r);if(c&&c.score>=.74){pos=Math.max(0,c.pos);conf=c.score;lastTick=performance.now();gate=true;setState('LOCK','LOCK · '+byN.get(SET[si]).title+' · '+fmt(pos));applyLine(pos,true);log('LOCK',{pos,score:c.score});}}
function transition(now){if(now-lastTrans<650||q.length<24||si>=SET.length-1)return;lastTrans=now;const qr=q.slice(-24),cur=global(qr,ref(SET[si])),nxt=global(qr,ref(SET[si+1]));if(!cur||!nxt)return;const strong=nxt.score>=.78&&(nxt.score-cur.score)>=.025;if(strong){if(voteSong===SET[si+1])votes++;else{voteSong=SET[si+1];votes=1;voteSince=now;}log('NEXT?',{cur:+cur.score.toFixed(3),next:+nxt.score.toFixed(3),votes});if(votes>=5&&now-voteSince>=1800){si++;pos=Math.max(0,nxt.pos);conf=nxt.score;votes=0;voteSong=0;render();setState('LOCK','CAMBIO SET · '+byN.get(SET[si]).title);applyLine(pos,true);log('SONG_SWITCH',{si,pos});}}else{votes=0;voteSong=0;}}
function loop(now){if(!stream)return;an.getByteFrequencyData(freq);const active=rms()>.012;if(active){lowSince=0;if(!gate){gate=true;lastTick=now;if(state==='SILENT')setState('LOCK','Audio reanudado desde '+fmt(pos));}if(now-lastF>=170){lastF=now;const f=feat();q.push(f);if(q.length>60)q.shift();}if(state==='ACQUIRE')acquire();if(state==='LOCK'){const dt=Math.max(0,Math.min(.25,(now-lastTick)/1000));pos+=dt;lastTick=now;applyLine(pos);if(now-lastLocal>=650&&q.length>=28){lastLocal=now;const c=local(q.slice(-28),ref(SET[si]),pos);if(c&&c.score>=.72){conf=c.score;const d=c.pos-pos;if(Math.abs(d)<=5){const corr=Math.max(-.28,Math.min(.28,d*.18));pos=Math.max(0,pos+corr);log('LOCAL',{d:+d.toFixed(2),corr:+corr.toFixed(2)});}}}transition(now);}}else{if(!lowSince)lowSince=now;if(state==='LOCK'&&now-lowSince>750){gate=false;setState('SILENT','Silencio · reloj congelado '+fmt(pos));log('SILENCE',{pos});}lastTick=now;}labels();raf=requestAnimationFrame(loop);}
U.play.onclick=()=>stream?stop(true):start();$('reset').onclick=reset;$('prevLine').onclick=()=>setLine(Math.max(0,line-1),true);$('nextLine').onclick=()=>setLine(line+1,true);$('find').onclick=()=>{if(stream){q=[];setState('ACQUIRE','BUSCAR · sólo canción actual del SET.');}};$('diagBtn').onclick=()=>U.diag.classList.toggle('hidden');U.select.onchange=()=>{si=+U.select.value;pos=0;q=[];votes=0;render();setState(stream?'ACQUIRE':'IDLE','SET '+(si+1)+'/'+SET.length+' seleccionado.');};
SET.forEach((n,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=(i+1)+'. '+byN.get(n).title;U.select.appendChild(o);});render();labels();
window.__cubabyCoreTest={dense,global,local,ref,SET};
})();